In [58]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [59]:
frecuencias_cardiacas = [[65],[70],[80],[80],[80],
                         [90],[95],[100],[105],[110],
                         [105],[110],[110],[120],[120],
                         [130],[140],[180],[185],[190]]

clase = [0,0,0,0,0,0,0,0,0,0,
         1,1,1,1,1,1,1,1,1,1]

In [60]:
datos_entrena,datos_prueba,clase_entrena,clase_prueba = train_test_split(frecuencias_cardiacas,clase,test_size=0.3)

In [61]:
modelo = LogisticRegression().fit(datos_entrena,clase_entrena)
np.set_printoptions(suppress=True) # Suprime la notacion cientifica
modelo.predict(datos_prueba)

array([1, 1, 0, 1, 1, 0])

In [62]:
modelo.predict_proba(datos_prueba)

array([[0.02881672, 0.97118328],
       [0.        , 1.        ],
       [0.98573496, 0.01426504],
       [0.00223353, 0.99776647],
       [0.        , 1.        ],
       [0.83905282, 0.16094718]])

In [63]:
modelo.score(datos_prueba,clase_prueba)

1.0

In [64]:
modelo.intercept_

array([-27.49498081])

In [65]:
modelo.coef_

array([[0.25843783]])